version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dependency_upgrades
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.2
  - dependency-name: ember-power-select
    versions:
    - 4.1.0
    - 4.1.2
  - dependency-name: ember-in-viewport
    versions:
    - 3.8.1
  - dependency-name: keen-tracking
    versions:
    - 4.5.1
  - dependency-name: ember-cli-typescript
    versions:
    - 4.0.0
