extends:
  - stylelint-config-css-modules
  - stylelint-config-sass-guidelines
plugins:
  - ./ember-osf-web-stylelint
rules:
  indentation: 4
  max-nesting-depth: 2
  order/properties-alphabetical-order: null
  scss/selector-no-redundant-nesting-selector: null
  scss/percent-placeholder-pattern: null
  selector-class-pattern: null
  property-no-unknown:
    - true
    - ignoreProperties:
      - composes
      - compose-with
  ember-osf-web-stylelint-plugin/no-unlocalized-selectors: true
