/* eslint-disable max-len */
/* eslint-disable max-len */

import SchemaBlock from 'ember-osf-web/models/schema-block';

const schemaBlocks: Array<Partial<SchemaBlock>> = [
    {
        displayText: 'Study Information',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 0,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5da4cf60f04bcd000155f3e6',
    },
    {
        displayText: 'Title',
        exampleText: "Effect of sugar on brownie tastiness. How responses will be evaluated: The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.",
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 1,
        required: false,
        helpText: 'Provide the working title of your study. It is helpful if this is the same title that you submit for publication of your final manuscript, but it is not a requirement.',
        schemaBlockGroupKey: '5da4cf60f04bcd000155f3e7',
        id: '5da4cf61f04bcd000155f3e8',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'q1',
        index: 2,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf60f04bcd000155f3e7',
        id: '5da4cf61f04bcd000155f3e9',
    },
    {
        displayText: 'Research Questions',
        exampleText: 'Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. How responses will be evaluated: The type of submissions for this question will vary widely by discipline, and we cannot determine if the question is worth asking. However, questions that are excessively vague so as to make understanding later sections difficult are not appropriate. For some studies, the research questions and hypotheses are extremely similar, so overlap between this and the subsequent question is expected.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 5,
        required: false,
        helpText: 'Please list each research question included in this study.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3ed',
        id: '5da4cf61f04bcd000155f3ee',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q3',
        index: 6,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3ed',
        id: '5da4cf61f04bcd000155f3ef',
    },
    {
        displayText: 'Hypotheses',
        exampleText: 'If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar.  How responses will be evaluated:  In this section, the submission should provide a prediction as to the outcome of the study or a statement that no specific prediction is expected.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 7,
        required: false,
        helpText: 'For each of the research questions listed in the previous section, provide one or multiple specific and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f0',
        id: '5da4cf61f04bcd000155f3f1',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q4',
        index: 8,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f0',
        id: '5da4cf61f04bcd000155f3f2',
    },
    {
        displayText: 'Sampling Plan',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 9,
        required: false,
        helpText: 'In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study.',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f3f3',
    },
    {
        displayText: 'Existing Data',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 10,
        required: false,
        helpText: 'Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io).',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f4',
        id: '5da4cf61f04bcd000155f3f5',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'q5',
        index: 11,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f4',
        id: '5da4cf61f04bcd000155f3f6',
    },
    {
        displayText: 'Registration prior to creation of data',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 12,
        required: false,
        helpText: 'As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f4',
        id: '5da4cf61f04bcd000155f3f7',
    },
    {
        displayText: 'Registration prior to any human observation of the data',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 13,
        required: false,
        helpText: 'As of the date of submission, the data exist but have not yet been quantified, constructed, observed, or reported by anyone - including individuals that are not associated with the proposed study. Examples include museum specimens that have not been measured and data that have been collected by non-human collectors and are inaccessible.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f4',
        id: '5da4cf61f04bcd000155f3f8',
    },
    {
        displayText: 'Registration prior to accessing the data',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 14,
        required: false,
        helpText: 'As of the date of submission, the data exist, but have not been accessed by you or your collaborators. Commonly, this includes data that has been collected by another researcher or institution.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f4',
        id: '5da4cf61f04bcd000155f3f9',
    },
    {
        displayText: 'Registration prior to analysis of the data',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 15,
        required: false,
        helpText: 'As of the date of submission, the data exist and you have accessed it, though no analysis has been conducted related to the research plan (including calculation of summary statistics). A common situation for this scenario when a large dataset exists that is used for many different studies over time, or when a data set is randomly split into a sample for exploratory analyses, and the other section of data is reserved for later confirmatory data analysis.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f4',
        id: '5da4cf61f04bcd000155f3fa',
    },
    {
        displayText: 'Registration following analysis of the data',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 16,
        required: false,
        helpText: 'As of the date of submission, you have accessed and analyzed some of the data relevant to the research plan. This includes preliminary analysis of variables, calculation of descriptive statistics, and observation of data distributions. Studies that fall into this category are ineligible for the Prereg Challenge. Please contact us (prereg@cos.io) and we will be happy to help you.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3f4',
        id: '5da4cf61f04bcd000155f3fb',
    },
    {
        displayText: 'Explanation of existing data',
        exampleText: ' An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.  How responses will be evaluated: Both confirmatory (hypothesis testing) and exploratory (hypothesis generating) analysis contribute to scientific progress, and do so best when it is clear which is which.  The Preregistration Challenge stimulates experience with preregistration of analysis plans for hypothesis testing, and transparency about the distinction between confirmatory and exploratory analysis. Research plans using existing data present unique challenges for hypothesis testing because observation of data can influence subsequent analysis plans of the same data. This can produce a gray area between confirmatory and exploratory analysis. Research plans using existing data may not be eligible for the Challenge. Determination of eligibility is based on evidence that the diagnosticity of the confirmatory analysis plans is retained despite the fact that the data exist.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 17,
        required: false,
        helpText: 'If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study. The purpose of this question is to assure that the line between confirmatory and exploratory analysis is clear.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3fc',
        id: '5da4cf61f04bcd000155f3fd',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q6',
        index: 18,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f3fc',
        id: '5da4cf61f04bcd000155f3fe',
    },
    {
        displayText: 'Data collection procedures',
        exampleText: '',
        blockType: 'section-heading',
        registrationResponseKey: null,
        index: 19,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f3ff',
    },
    {
        displayText: 'Data collection procedures',
        exampleText: 'Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. How responses will be evaluated: The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 20,
        required: false,
        helpText: 'Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that don’t include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f400',
        id: '5da4cf61f04bcd000155f401',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q7.question',
        index: 21,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f400',
        id: '5da4cf61f04bcd000155f402',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 22,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f403',
        id: '5da4cf61f04bcd000155f404',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'file-input',
        registrationResponseKey: 'q7.uploader',
        index: 23,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f403',
        id: '5da4cf61f04bcd000155f405',
    },
    {
        displayText: 'Sample size',
        exampleText: 'Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task.  How responses will be evaluated: For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 24,
        required: false,
        helpText: 'Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis?',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f406',
        id: '5da4cf61f04bcd000155f407',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q8',
        index: 25,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f406',
        id: '5da4cf61f04bcd000155f408',
    },
    {
        displayText: 'Sample size rationale',
        exampleText: 'We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability.  How responses will be evaluated: This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to “fill in the blanks.” Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 26,
        required: false,
        helpText: 'This could include a power analysis or an arbitrary constraint such as time, money, or personnel.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f409',
        id: '5da4cf61f04bcd000155f40a',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q9',
        index: 27,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f409',
        id: '5da4cf61f04bcd000155f40b',
    },
    {
        displayText: 'Stopping rule',
        exampleText: 'We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants.  How responses will be evaluated: You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 28,
        required: false,
        helpText: 'If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. ',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f40c',
        id: '5da4cf61f04bcd000155f40d',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q10',
        index: 29,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f40c',
        id: '5da4cf61f04bcd000155f40e',
    },
    {
        displayText: 'Variables',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 30,
        required: false,
        helpText: 'In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so.',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f40f',
    },
    {
        displayText: 'Manipulated variables',
        exampleText: '',
        blockType: 'section-heading',
        registrationResponseKey: null,
        index: 31,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f410',
    },
    {
        displayText: 'Manipulated variables',
        exampleText: "We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass.  How responses will be evaluated: For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.",
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 32,
        required: false,
        helpText: 'Describe all variables you plan to manipulate and the levels or treatment arms of each variable. For observational studies and meta-analyses, simply state that this is not applicable.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f411',
        id: '5da4cf61f04bcd000155f412',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q11.question',
        index: 33,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f411',
        id: '5da4cf61f04bcd000155f413',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 34,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f414',
        id: '5da4cf61f04bcd000155f415',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'file-input',
        registrationResponseKey: 'q11.uploader',
        index: 35,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f414',
        id: '5da4cf61f04bcd000155f416',
    },
    {
        displayText: 'Measured variables',
        exampleText: '',
        blockType: 'section-heading',
        registrationResponseKey: null,
        index: 36,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f417',
    },
    {
        displayText: 'Measured variables',
        exampleText: "The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being ‘not at all’, 7 being ‘a great deal’) and ‘How good did the brownie taste’ (on a scale of 1-7, 1 being ‘very bad’, 7 being ‘very good’).  How responses will be evaluated: Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be  'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.' ",
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 37,
        required: false,
        helpText: 'Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f418',
        id: '5da4cf61f04bcd000155f419',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q12.question',
        index: 38,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f418',
        id: '5da4cf61f04bcd000155f41a',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 39,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f41b',
        id: '5da4cf61f04bcd000155f41c',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'file-input',
        registrationResponseKey: 'q12.uploader',
        index: 40,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f41b',
        id: '5da4cf61f04bcd000155f41d',
    },
    {
        displayText: 'Indices',
        exampleText: '',
        blockType: 'section-heading',
        registrationResponseKey: null,
        index: 41,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f41e',
    },
    {
        displayText: 'Indices',
        exampleText: 'We will take the mean of the two questions above to create a single measure of ‘brownie enjoyment.’  How responses will be evaluated: If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as “means” do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, “biodiversity index” is too broad, whereas “Shannon’s biodiversity index” is appropriate.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 42,
        required: false,
        helpText: 'If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f41f',
        id: '5da4cf61f04bcd000155f420',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q13.question',
        index: 43,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f41f',
        id: '5da4cf61f04bcd000155f421',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 44,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f422',
        id: '5da4cf61f04bcd000155f423',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'file-input',
        registrationResponseKey: 'q13.uploader',
        index: 45,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f422',
        id: '5da4cf61f04bcd000155f424',
    },
    {
        displayText: 'Design Plan',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 46,
        required: false,
        helpText: 'In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration.',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f425',
    },
    {
        displayText: 'Study type',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 47,
        required: false,
        helpText: 'Please check one of the following statements',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f426',
        id: '5da4cf61f04bcd000155f427',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'q14',
        index: 48,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f426',
        id: '5da4cf61f04bcd000155f428',
    },
    {
        displayText: 'Experiment - A researcher randomly assigns treatments to study subjects, this includes field or lab experiments. This is also known as an intervention experiment and includes randomized controlled trials.',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 49,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f426',
        id: '5da4cf61f04bcd000155f429',
    },
    {
        displayText: 'Observational Study - Data is collected from study subjects that are not randomly assigned to a treatment. This includes surveys, “natural experiments,” and regression discontinuity designs.',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 50,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f426',
        id: '5da4cf61f04bcd000155f42a',
    },
    {
        displayText: 'Meta-Analysis - A systematic review of published studies.',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 51,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f426',
        id: '5da4cf61f04bcd000155f42b',
    },
    {
        displayText: 'Other',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 52,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f426',
        id: '5da4cf61f04bcd000155f42c',
    },
    {
        displayText: 'Blinding',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 53,
        required: false,
        helpText: 'Blinding describes who is aware of the experimental manipulations within a study. Mark all that apply.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f42d',
        id: '5da4cf61f04bcd000155f42e',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'multi-select-input',
        registrationResponseKey: 'q15',
        index: 54,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f42d',
        id: '5da4cf61f04bcd000155f42f',
    },
    {
        displayText: 'No blinding is involved in this study.',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 55,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f42d',
        id: '5da4cf61f04bcd000155f430',
    },
    {
        displayText: 'For studies that involve human subjects, they will not know the treatment group to which they have been assigned.',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 56,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f42d',
        id: '5da4cf61f04bcd000155f431',
    },
    {
        displayText: 'Research personnel who interact directly with the study subjects (either human or non-human subjects) will not be aware of the assigned treatments.',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 57,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f42d',
        id: '5da4cf61f04bcd000155f432',
    },
    {
        displayText: 'Research personnel who analyze the data collected from the study are not aware of the treatment applied to any given group.',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 58,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f42d',
        id: '5da4cf61f04bcd000155f433',
    },
    {
        displayText: 'Study design',
        exampleText: '',
        blockType: 'section-heading',
        registrationResponseKey: null,
        index: 59,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f434',
    },
    {
        displayText: 'Study design',
        exampleText: 'We have a between subjects design with 1 factor (sugar by mass) with 4 levels.  How responses will be evaluated: This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 60,
        required: false,
        helpText: 'Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies. ',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f435',
        id: '5da4cf61f04bcd000155f436',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q16.question',
        index: 61,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f435',
        id: '5da4cf61f04bcd000155f437',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 62,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f438',
        id: '5da4cf61f04bcd000155f439',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'file-input',
        registrationResponseKey: 'q16.uploader',
        index: 63,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f438',
        id: '5da4cf61f04bcd000155f43a',
    },
    {
        displayText: 'Randomization',
        exampleText: 'We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at http://random.org.  How responses will be evaluated: Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 64,
        required: false,
        helpText: 'If you are doing a randomized study, how will you randomize, and at what level? ',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f43b',
        id: '5da4cf61f04bcd000155f43c',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q17',
        index: 65,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f43b',
        id: '5da4cf61f04bcd000155f43d',
    },
    {
        displayText: 'Analysis Plan',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 66,
        required: false,
        helpText: 'You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis-generating.A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required.',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f43e',
    },
    {
        displayText: 'Statistical models',
        exampleText: '',
        blockType: 'section-heading',
        registrationResponseKey: null,
        index: 67,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5da4cf61f04bcd000155f43f',
    },
    {
        displayText: 'Statistical models',
        exampleText: "We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index.  How responses will be evaluated: This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples: If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.",
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 68,
        required: false,
        helpText: 'What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions that will be tested and remember that any test not included here must be noted as an exploratory test in your final article.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f440',
        id: '5da4cf61f04bcd000155f441',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q19.question',
        index: 69,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f440',
        id: '5da4cf61f04bcd000155f442',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 70,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f443',
        id: '5da4cf61f04bcd000155f444',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'file-input',
        registrationResponseKey: 'q19.uploader',
        index: 71,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f443',
        id: '5da4cf61f04bcd000155f445',
    },
    {
        displayText: 'Transformations',
        exampleText: 'The “Effect of sugar on brownie tastiness” does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), ‘sweet’ could be dummy coded with ‘not sweet’ as the reference category.  How responses will be evaluated: If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 72,
        required: false,
        helpText: 'If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f446',
        id: '5da4cf61f04bcd000155f447',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q20',
        index: 73,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f446',
        id: '5da4cf61f04bcd000155f448',
    },
    {
        displayText: 'Follow-up analyses',
        exampleText: 'If the the ANOVA indicates that the mean taste perceptions are significantly different (p&lt;.05), then we will use a Tukey-Kramer HSD test to conduct all possible pairwise comparison. How responses will be evaluated: This is simply a place to allow entering in any additional analyses. The criteria for these follow up analyses are identical to any analyses listed in other sections. It is also fine to enter these follow up analyses in a separate analysis section. The purpose of this question is to allow entering of any follow up tests that naturally follow from a primary analysis.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 74,
        required: false,
        helpText: 'If not specified previously, will you be conducting any confirmatory analyses to follow up on effects in your statistical model, such as subgroup analyses, pairwise or complex contrasts, or follow-up tests from interactions? Remember that any analyses not specified in this research plan must be noted as exploratory.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f449',
        id: '5da4cf61f04bcd000155f44a',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q21',
        index: 75,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f449',
        id: '5da4cf61f04bcd000155f44b',
    },
    {
        displayText: 'Inference criteria',
        exampleText: 'We will use the standard p&lt;.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. How responses will be evaluated: P-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few “wrong” answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 76,
        required: false,
        helpText: 'What criteria will you use to make inferences? Please describe the information you’ll use (e.g. specify the p-values, Bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this? ',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f44c',
        id: '5da4cf61f04bcd000155f44d',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q22',
        index: 77,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f44c',
        id: '5da4cf61f04bcd000155f44e',
    },
    {
        displayText: 'Data exclusion',
        exampleText: 'No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis.  How responses will be evaluated: Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 78,
        required: false,
        helpText: 'How will you determine which data points or samples (if any) to exclude from your analyses? How will outliers be handled?',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f44f',
        id: '5da4cf61f04bcd000155f450',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q23',
        index: 79,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f44f',
        id: '5da4cf61f04bcd000155f451',
    },
    {
        displayText: 'Missing data',
        exampleText: 'If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. How responses will be evaluated:  Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 80,
        required: false,
        helpText: 'How will you deal with incomplete or missing data?',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f452',
        id: '5da4cf61f04bcd000155f453',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q24',
        index: 81,
        required: true,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f452',
        id: '5da4cf61f04bcd000155f454',
    },
    {
        displayText: 'Exploratory analysis',
        exampleText: 'We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences.',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 82,
        required: false,
        helpText: 'If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f455',
        id: '5da4cf62f04bcd000155f456',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q25',
        index: 83,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf61f04bcd000155f455',
        id: '5da4cf62f04bcd000155f457',
    },
    {
        displayText: 'Scripts',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 84,
        required: false,
        helpText: 'The purpose of a fully commented analysis script is to unambiguously provide the responses to all of the questions raised in the analysis section. This step is not common, but we encourage you to try creating an analysis script, refine it using a modeled dataset, and use it in place of your written analysis plan.',
        schemaBlockGroupKey: '',
        id: '5da4cf62f04bcd000155f458',
    },
    {
        displayText: 'Upload an analysis script with clear comments',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 85,
        required: false,
        helpText: 'This optional step is helpful in order to create a process that is completely transparent and increase the likelihood that your analysis can be replicated. We recommend that you run the code on a simulated dataset in order to check that it will run without errors.',
        schemaBlockGroupKey: '5da4cf62f04bcd000155f459',
        id: '5da4cf62f04bcd000155f45a',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'file-input',
        registrationResponseKey: 'q26',
        index: 86,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf62f04bcd000155f459',
        id: '5da4cf62f04bcd000155f45b',
    },
    {
        displayText: 'Other',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 87,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5da4cf62f04bcd000155f45c',
    },
    {
        displayText: 'Other',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 88,
        required: false,
        helpText: 'If there is any additional information that you feel needs to be included in your preregistration, please enter it here.',
        schemaBlockGroupKey: '5da4cf62f04bcd000155f45d',
        id: '5da4cf62f04bcd000155f45e',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'q27',
        index: 89,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5da4cf62f04bcd000155f45d',
        id: '5da4cf62f04bcd000155f45f',
    },
];

export const schemaBlockIds = schemaBlocks.map(block => block.id);

export default schemaBlocks;

/* eslint-enable max-len */
