/* eslint-disable max-len */
/* eslint-disable max-len */

import SchemaBlock from 'ember-osf-web/models/schema-block';

const schemaBlocks: Array<Partial<SchemaBlock>> = [
    {
        displayText: 'The Nature of the Effect',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 0,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5dc321a0bd8f2d00016d4f2e',
    },
    {
        displayText: 'Verbal description of the effect I am trying to replicate',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 1,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f2f',
        id: '5dc321a0bd8f2d00016d4f30',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item1',
        index: 2,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f2f',
        id: '5dc321a0bd8f2d00016d4f31',
    },
    {
        displayText: 'It is important to replicate this effect because',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 3,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f32',
        id: '5dc321a0bd8f2d00016d4f33',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item2',
        index: 4,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f32',
        id: '5dc321a0bd8f2d00016d4f34',
    },
    {
        displayText: 'The effect size of the effect I am trying to replicate is',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 5,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f35',
        id: '5dc321a0bd8f2d00016d4f36',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item3',
        index: 6,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f35',
        id: '5dc321a0bd8f2d00016d4f37',
    },
    {
        displayText: 'The confidence interval of the original effect is',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 7,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f38',
        id: '5dc321a0bd8f2d00016d4f39',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item4',
        index: 8,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f38',
        id: '5dc321a0bd8f2d00016d4f3a',
    },
    {
        displayText: 'The sample size of the original effect is',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 9,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f3b',
        id: '5dc321a0bd8f2d00016d4f3c',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item5',
        index: 10,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f3b',
        id: '5dc321a0bd8f2d00016d4f3d',
    },
    {
        displayText: 'Where was the original study conducted? (e.g., lab, in the field, online)',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 11,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f3e',
        id: '5dc321a0bd8f2d00016d4f3f',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item6',
        index: 12,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f3e',
        id: '5dc321a0bd8f2d00016d4f40',
    },
    {
        displayText: 'What country/region was the original study conducted in?',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 13,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f41',
        id: '5dc321a0bd8f2d00016d4f42',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item7',
        index: 14,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f41',
        id: '5dc321a0bd8f2d00016d4f43',
    },
    {
        displayText: 'What kind of sample did the original study use? (e.g., student, Mturk, representative)',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 15,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f44',
        id: '5dc321a0bd8f2d00016d4f45',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item8',
        index: 16,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f44',
        id: '5dc321a0bd8f2d00016d4f46',
    },
    {
        displayText: 'Was the original study conducted with paper-and-pencil surveys, on a computer, or something else?',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 17,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f47',
        id: '5dc321a0bd8f2d00016d4f48',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item9',
        index: 18,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f47',
        id: '5dc321a0bd8f2d00016d4f49',
    },
    {
        displayText: 'Designing the Replication Study',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 19,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5dc321a0bd8f2d00016d4f4a',
    },
    {
        displayText: 'Are the original materials for the study available from the author?',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 20,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f4b',
        id: '5dc321a0bd8f2d00016d4f4c',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'item10',
        index: 21,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f4b',
        id: '5dc321a0bd8f2d00016d4f4d',
    },
    {
        displayText: 'yes',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 22,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f4b',
        id: '5dc321a0bd8f2d00016d4f4e',
    },
    {
        displayText: 'no',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 23,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f4b',
        id: '5dc321a0bd8f2d00016d4f4f',
    },
    {
        displayText: 'I know that assumptions (e.g., about the meaning of the stimuli) in the original study will also hold in my replication because',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 24,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f50',
        id: '5dc321a0bd8f2d00016d4f51',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item11',
        index: 25,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f50',
        id: '5dc321a0bd8f2d00016d4f52',
    },
    {
        displayText: 'Location of the experimenter during data collection',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 26,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f53',
        id: '5dc321a0bd8f2d00016d4f54',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item12',
        index: 27,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f53',
        id: '5dc321a0bd8f2d00016d4f55',
    },
    {
        displayText: 'Experimenter knowledge of participant experimental condition',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 28,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f56',
        id: '5dc321a0bd8f2d00016d4f57',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item13',
        index: 29,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f56',
        id: '5dc321a0bd8f2d00016d4f58',
    },
    {
        displayText: 'Experimenter knowledge of overall hypotheses',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 30,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f59',
        id: '5dc321a0bd8f2d00016d4f5a',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item14',
        index: 31,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f59',
        id: '5dc321a0bd8f2d00016d4f5b',
    },
    {
        displayText: 'My target sample size is',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 32,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f5c',
        id: '5dc321a0bd8f2d00016d4f5d',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item15',
        index: 33,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f5c',
        id: '5dc321a0bd8f2d00016d4f5e',
    },
    {
        displayText: 'The rationale for my sample size is',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 34,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f5f',
        id: '5dc321a0bd8f2d00016d4f60',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'short-text-input',
        registrationResponseKey: 'item16',
        index: 35,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f5f',
        id: '5dc321a0bd8f2d00016d4f61',
    },
    {
        displayText: 'Documenting Differences between the Original and Replication Study',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 36,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5dc321a0bd8f2d00016d4f62',
    },
    {
        displayText: 'The similarities/differences in the instructions are',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 37,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f63',
        id: '5dc321a0bd8f2d00016d4f64',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'item17',
        index: 38,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f63',
        id: '5dc321a0bd8f2d00016d4f65',
    },
    {
        displayText: 'Exact',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 39,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f63',
        id: '5dc321a0bd8f2d00016d4f66',
    },
    {
        displayText: 'Close',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 40,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f63',
        id: '5dc321a0bd8f2d00016d4f67',
    },
    {
        displayText: 'Different',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 41,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f63',
        id: '5dc321a0bd8f2d00016d4f68',
    },
    {
        displayText: 'The similarities/differences in the measures are',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 42,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f69',
        id: '5dc321a0bd8f2d00016d4f6a',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'item18',
        index: 43,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f69',
        id: '5dc321a0bd8f2d00016d4f6b',
    },
    {
        displayText: 'Exact',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 44,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f69',
        id: '5dc321a0bd8f2d00016d4f6c',
    },
    {
        displayText: 'Close',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 45,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f69',
        id: '5dc321a0bd8f2d00016d4f6d',
    },
    {
        displayText: 'Different',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 46,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f69',
        id: '5dc321a0bd8f2d00016d4f6e',
    },
    {
        displayText: 'The similarities/differences in the stimuli are',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 47,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f6f',
        id: '5dc321a0bd8f2d00016d4f70',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'item19',
        index: 48,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f6f',
        id: '5dc321a0bd8f2d00016d4f71',
    },
    {
        displayText: 'Exact',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 49,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f6f',
        id: '5dc321a0bd8f2d00016d4f72',
    },
    {
        displayText: 'Close',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 50,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f6f',
        id: '5dc321a0bd8f2d00016d4f73',
    },
    {
        displayText: 'Different',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 51,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f6f',
        id: '5dc321a0bd8f2d00016d4f74',
    },
    {
        displayText: 'The similarities/differences in the procedure are',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 52,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f75',
        id: '5dc321a0bd8f2d00016d4f76',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'item20',
        index: 53,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f75',
        id: '5dc321a0bd8f2d00016d4f77',
    },
    {
        displayText: 'Exact',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 54,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f75',
        id: '5dc321a0bd8f2d00016d4f78',
    },
    {
        displayText: 'Close',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 55,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f75',
        id: '5dc321a0bd8f2d00016d4f79',
    },
    {
        displayText: 'Different',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 56,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f75',
        id: '5dc321a0bd8f2d00016d4f7a',
    },
    {
        displayText: 'The similarities/differences in the location (e.g., lab vs. online; alone vs. in groups) are',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 57,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f7b',
        id: '5dc321a0bd8f2d00016d4f7c',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'item21',
        index: 58,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f7b',
        id: '5dc321a0bd8f2d00016d4f7d',
    },
    {
        displayText: 'Exact',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 59,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f7b',
        id: '5dc321a0bd8f2d00016d4f7e',
    },
    {
        displayText: 'Close',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 60,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f7b',
        id: '5dc321a0bd8f2d00016d4f7f',
    },
    {
        displayText: 'Different',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 61,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f7b',
        id: '5dc321a0bd8f2d00016d4f80',
    },
    {
        displayText: 'The similarities/difference in remuneration are',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 62,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f81',
        id: '5dc321a0bd8f2d00016d4f82',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'item22',
        index: 63,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f81',
        id: '5dc321a0bd8f2d00016d4f83',
    },
    {
        displayText: 'Exact',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 64,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f81',
        id: '5dc321a0bd8f2d00016d4f84',
    },
    {
        displayText: 'Close',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 65,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f81',
        id: '5dc321a0bd8f2d00016d4f85',
    },
    {
        displayText: 'Different',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 66,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f81',
        id: '5dc321a0bd8f2d00016d4f86',
    },
    {
        displayText: 'The similarities/differences between participant populations are',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 67,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f87',
        id: '5dc321a0bd8f2d00016d4f88',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'single-select-input',
        registrationResponseKey: 'item23',
        index: 68,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f87',
        id: '5dc321a0bd8f2d00016d4f89',
    },
    {
        displayText: 'Exact',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 69,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f87',
        id: '5dc321a0bd8f2d00016d4f8a',
    },
    {
        displayText: 'Close',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 70,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f87',
        id: '5dc321a0bd8f2d00016d4f8b',
    },
    {
        displayText: 'Different',
        exampleText: '',
        blockType: 'select-input-option',
        registrationResponseKey: null,
        index: 71,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f87',
        id: '5dc321a0bd8f2d00016d4f8c',
    },
    {
        displayText: 'What differences between the original study and your study might be expected to influence the size and/or direction of the effect?',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 72,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f8d',
        id: '5dc321a0bd8f2d00016d4f8e',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item24',
        index: 73,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f8d',
        id: '5dc321a0bd8f2d00016d4f8f',
    },
    {
        displayText: 'I have taken the following steps to test whether the differences listed in the previous question will influence the outcome of my replication attempt',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 74,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f90',
        id: '5dc321a0bd8f2d00016d4f91',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item25',
        index: 75,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f90',
        id: '5dc321a0bd8f2d00016d4f92',
    },
    {
        displayText: 'Analysis and Replication Evaluation',
        exampleText: '',
        blockType: 'page-heading',
        registrationResponseKey: null,
        index: 76,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '',
        id: '5dc321a0bd8f2d00016d4f93',
    },
    {
        displayText: 'My exclusion criteria are (e.g., handling outliers, removing participants from analysis)',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 77,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f94',
        id: '5dc321a0bd8f2d00016d4f95',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item26',
        index: 78,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f94',
        id: '5dc321a0bd8f2d00016d4f96',
    },
    {
        displayText: 'My analysis plan is (justify differences from the original)',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 79,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f97',
        id: '5dc321a0bd8f2d00016d4f98',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item27',
        index: 80,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a0bd8f2d00016d4f97',
        id: '5dc321a0bd8f2d00016d4f99',
    },
    {
        displayText: 'A successful replication is defined as',
        exampleText: '',
        blockType: 'question-label',
        registrationResponseKey: null,
        index: 81,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a1bd8f2d00016d4f9a',
        id: '5dc321a1bd8f2d00016d4f9b',
    },
    {
        displayText: '',
        exampleText: '',
        blockType: 'long-text-input',
        registrationResponseKey: 'item28',
        index: 82,
        required: false,
        helpText: '',
        schemaBlockGroupKey: '5dc321a1bd8f2d00016d4f9a',
        id: '5dc321a1bd8f2d00016d4f9c',
    },
];

export const schemaBlockIds = schemaBlocks.map(block => block.id);

export default schemaBlocks;

/* eslint-enable max-len */
