{
	"took": 38,
	"timed_out": false,
	"hits": {
		"total": 5,
		"hits": [{
			"_index": "share_customtax_1",
			"_type": "creativeworks",
			"_id": "4614E-CF4-5BB",
			"_score": null,
			"_source": {
			"sort": [1501436071234]
		}, {
			"_index": "share_customtax_1",
			"_type": "creativeworks",
			"_id": "4607B-B78-676",
			"_score": null,
			"_source": {
				"registration_type": "Prereg Challenge",
				"date_created": "2017-01-10T02:18:23.8136+00:00",
				"identifiers": ["urn://share/io.osf.registrations:2ds52", "http://api.osf.io/v2/registrations/2ds52/", "http://osf.io/2ds52/"],
				"date_updated": "2017-05-15T12:00:17.208642+00:00",
				"subject_synonyms": [],
				"lists": {
					"contributors": [{
						"affiliations": [],
						"types": ["person", "agent"],
						"awards": [],
						"name": "Stephen Politzer-Ahles",
						"relation": "creator",
						"identifiers": ["http://secure.gravatar.com/avatar/b1afd58c6037bd4187750c79e13a388a?d=identicon", "http://osf.io/y2cjh/"],
						"type": "person",
						"cited_as": "Stephen Politzer-Ahles",
						"given_name": "Stephen",
						"id": "641DC-FCC-EF4",
						"family_name": "Politzer-Ahles",
						"order_cited": 0
					}, {
						"additional_name": "Matthew",
						"affiliations": [],
						"types": ["person", "agent"],
						"awards": [],
						"name": "Edward Matthew Husband",
						"relation": "creator",
						"identifiers": ["http://secure.gravatar.com/avatar/eff58160dae3624239cd9ba909907459?d=identicon", "http://osf.io/cw5hy/"],
						"type": "person",
						"cited_as": "Edward Matthew Husband",
						"given_name": "Edward",
						"id": "6401C-9F3-FC1",
						"family_name": "Husband",
						"order_cited": 1
					}]
				},
				"withdrawn": false,
				"id": "4607B-B78-676",
				"retracted": false,
				"justification": null,
				"affiliations": [],
				"language": null,
				"sources": ["OSF"],
				"tags": ["project"],
				"date_published": "2016-03-13T23:01:15.73+00:00",
				"type": "registration",
				"contributors": ["Stephen Politzer-Ahles", "Edward Matthew Husband"],
				"date_modified": "2017-05-16T01:01:41.904167+00:00",
				"subjects": [],
				"types": ["registration", "publication", "creative work"],
				"date": "2016-03-13T23:01:15.73+00:00",
				"title": "Pragmatic adaptation: testing whether inference judgments are susceptible to bias over the course of an experiment",
				"description": ""
			},
			"sort": [1494849617208]
		}, {
			"_index": "share_customtax_1",
			"_type": "creativeworks",
			"_id": "46078-26C-768",
			"_score": null,
			"_source": {
				"date_published": "2016-08-10T20:24:42.872+00:00",
				"justification": null,
				"description": "",
				"date_created": "2017-02-20T18:34:30.281756+00:00",
				"identifiers": ["http://osf.io/2tpy9/"],
				"withdrawn": false,
				"subject_synonyms": [],
				"language": null,
				"tags": [],
				"lists": {
					"contributors": [{
						"given_name": "Emilia",
						"types": ["person", "agent"],
						"awards": [],
						"name": "Emilia Ninova",
						"type": "person",
						"relation": "creator",
						"identifiers": ["http://secure.gravatar.com/avatar/0d9797aa18d31e2ff7e94868b17b7678?d=identicon", "http://osf.io/5tgnd/"],
						"affiliations": [],
						"id": "64041-E8E-8A9",
						"order_cited": 1,
						"cited_as": "Emilia Ninova",
						"family_name": "Ninova"
					}, {
						"awards": [],
						"given_name": "Jennifer",
						"types": ["person", "agent"],
						"affiliations": [],
						"additional_name": "A",
						"name": "Jennifer A Silvers",
						"type": "person",
						"relation": "creator",
						"identifiers": ["http://secure.gravatar.com/avatar/a8e3f38f672b9baa151a80e4b99dedfd?d=identicon", "http://osf.io/tz85r/"],
						"family_name": "Silvers",
						"id": "6403B-333-421",
						"order_cited": 2,
						"cited_as": "Jennifer Silvers"
					}, {
						"awards": [],
						"given_name": "Joao",
						"types": ["person", "agent"],
						"affiliations": [],
						"additional_name": "F Guassi",
						"name": "Joao F Guassi Moreira",
						"type": "person",
						"relation": "creator",
						"identifiers": ["http://secure.gravatar.com/avatar/8a29a1eae2f8cbc2727dd0220119c0c5?d=identicon", "http://osf.io/38e4d/"],
						"family_name": "Moreira",
						"id": "6416F-49B-4ED",
						"order_cited": 0,
						"cited_as": "Joao F. Guassi Moreira"
					}]
				},
				"affiliations": [],
				"retracted": false,
				"type": "registration",
				"contributors": ["Emilia Ninova", "Jennifer Silvers", "Joao F. Guassi Moreira"],
				"registration_type": "Prereg Challenge",
				"date_modified": "2017-02-20T18:34:30.281738+00:00",
				"date_updated": null,
				"subjects": [],
				"id": "46078-26C-768",
				"types": ["registration", "publication", "creative work"],
				"title": "Does Practicing Cognitive Reappraisal Enhance Impulse Inhibition during Subsequent Risk Taking?",
				"sources": ["OSF"],
				"date": "2016-08-10T20:24:42.872+00:00"
			},
			"sort": [-9223372036854775808]
		}, {
			"_index": "share_customtax_1",
			"_type": "creativeworks",
			"_id": "4613A-4DE-54B",
			"_score": null,
			"_source": {
				"language": null,
				"type": "registration",
				"affiliations": [],
				"subjects": [],
				"description": "",
				"registration_type": "Prereg Challenge",
				"date_updated": null,
				"justification": null,
				"sources": ["OSF"],
				"withdrawn": false,
				"title": "Local predictors of variation in plant phenology",
				"lists": {
					"contributors": [{
						"type": "person",
						"types": ["person", "agent"],
						"awards": [],
						"identifiers": ["http://osf.io/kz5tm/", "http://secure.gravatar.com/avatar/71912f8e693a4004a22b9053cb12dd65?d=identicon"],
						"affiliations": [],
						"relation": "creator",
						"name": "Margaret Kosmala",
						"id": "6411E-3C9-8DE",
						"order_cited": 0,
						"family_name": "Kosmala",
						"given_name": "Margaret",
						"cited_as": "Margaret Kosmala"
					}]
				},
				"types": ["registration", "publication", "creative work"],
				"id": "4613A-4DE-54B",
				"date": "2016-11-07T21:19:08.885+00:00",
				"subject_synonyms": [],
				"contributors": ["Margaret Kosmala"],
				"date_created": "2017-02-20T18:36:38.569206+00:00",
				"retracted": false,
				"identifiers": ["http://osf.io/6tsnj/"],
				"date_modified": "2017-02-20T18:36:38.569187+00:00",
				"tags": [],
				"date_published": "2016-11-07T21:19:08.885+00:00"
			},
			"sort": [-9223372036854775808]
		}, {
			"_index": "share_customtax_1",
			"_type": "creativeworks",
			"_id": "461C9-071-D7E",
			"_score": null,
			"_source": {
				"date_published": "2016-10-13T19:46:07.85+00:00",
				"justification": null,
				"description": "",
				"date_created": "2017-02-20T18:36:05.787417+00:00",
				"identifiers": ["http://osf.io/e94t8/"],
				"withdrawn": false,
				"subject_synonyms": [],
				"language": null,
				"tags": [],
				"lists": {
					"contributors": [{
						"given_name": "Geoffrey",
						"types": ["person", "agent"],
						"awards": [],
						"name": "Geoffrey Borman",
						"type": "person",
						"relation": "creator",
						"identifiers": ["http://secure.gravatar.com/avatar/b3321a754ad87879dcaf606ab3eded62?d=identicon", "http://osf.io/krv2n/"],
						"affiliations": [],
						"id": "640F4-182-386",
						"order_cited": 0,
						"cited_as": "Geoffrey Borman",
						"family_name": "Borman"
					}, {
						"given_name": "Jon",
						"types": ["person", "agent"],
						"awards": [],
						"name": "Jon Baron",
						"type": "person",
						"relation": "creator",
						"identifiers": ["http://secure.gravatar.com/avatar/38b6d12d7e39cbf3fc5c80cbf2d7f316?d=identicon", "http://osf.io/g5m30/"],
						"affiliations": [{
							"type": "institution",
							"affiliation": "is affiliated with",
							"types": ["institution", "organization", "agent"],
							"name": "Laura and John Arnold Foundation",
							"id": "64208-096-3C0"
						}],
						"id": "640A4-91F-24F",
						"order_cited": 1,
						"cited_as": "Jon Baron",
						"family_name": "Baron"
					}]
				},
				"affiliations": ["Laura and John Arnold Foundation"],
				"retracted": false,
				"type": "registration",
				"contributors": ["Geoffrey Borman", "Jon Baron"],
				"registration_type": "Prereg Challenge",
				"date_modified": "2017-02-20T18:36:05.787438+00:00",
				"date_updated": null,
				"subjects": [],
				"id": "461C9-071-D7E",
				"types": ["registration", "publication", "creative work"],
				"title": "Promoting School Belongingness and Academic Performance: A Multisite Effectiveness Trial of a Scalable Student Mindset Intervention",
				"sources": ["OSF"],
				"date": "2016-10-13T19:46:07.85+00:00"
			},
			"sort": [-9223372036854775808]
		}]
	}
}


const oneRegistration = {
				"date": "2016-09-09T03:17:35.798+00:00",
				"date_published": "2016-09-09T03:17:35.798+00:00",
				"justification": null,
				"sources": ["OSF"],
				"affiliations": [],
				"registration_type": "Prereg Challenge",
				"type": "registration",
				"subject_synonyms": [],
				"id": "4614E-CF4-5BB",
				"language": null,
				"types": ["registration", "publication", "creative work"],
				"lists": {
					"contributors": [{
						"affiliations": [],
						"awards": [],
						"family_name": "Sullivan",
						"given_name": "Jess",
						"order_cited": 1,
						"relation": "creator",
						"name": "Jess Sullivan",
						"cited_as": "Jess Sullivan",
						"type": "person",
						"identifiers": ["http://secure.gravatar.com/avatar/cc4c925e9364bfa84f293d009a19df61?d=identicon", "http://osf.io/xbjyd/"],
						"id": "640F9-6AC-488",
						"types": ["person", "agent"]
					}, {
						"affiliations": [],
						"awards": [],
						"family_name": "Deutchman",
						"given_name": "Paul",
						"types": ["person", "agent"],
						"order_cited": 0,
						"relation": "creator",
						"name": "Paul Michael Deutchman",
						"cited_as": "Paul Michael Deutchman",
						"type": "person",
						"identifiers": ["http://secure.gravatar.com/avatar/6bffdffd2515a211b5121ab9546a64cf?d=identicon", "http://osf.io/6khef/"],
						"id": "64229-6B9-B38",
						"additional_name": "Michael"
					}]
				},
				"subjects": [],
				"title": "2016, Deutchman, The Role of Framing Effects, the Dark Triad, and Empathy in Predicting Behavior in a One-shot Prisoner's Dilemma",
				"retracted": false,
				"contributors": ["Jess Sullivan", "Paul Michael Deutchman"],
				"date_updated": "2017-07-30T17:34:31.234631+00:00",
				"description": "This project is designed to support Haverford College economics majors who produce empirical theses. The structure is based on the TIER Documentation Protocol. Additional information about Project TIER is available at http://projecttier.org",
				"date_modified": "2017-07-31T02:26:51.566149+00:00",
				"date_created": "2016-12-07T18:00:39.914615+00:00",
				"tags": ["project"],
				"withdrawn": false,
				"identifiers": ["urn://share/io.osf.registrations:aurjt", "http://api.osf.io/v2/registrations/aurjt/", "http://osf.io/aurjt/"]
			},
}
