import { Factory, ModelInstance } from 'ember-cli-mirage';
import faker from 'faker';

import CollectionSubmission, { CollectionSubmissionReviewStates } from 'ember-osf-web/models/collection-submission';
import UserModel from 'ember-osf-web/models/user';

import { CollectionSubmissionActionTrigger } from 'ember-osf-web/models/collection-submission-action';

import { guid, guidAfterCreate } from './utils';

/**
 * MirageSubmissionAction
 *
 * @description Used for typing of thye submission action
 */
export interface MirageSubmissionAction {
    /**
     * The comment for the collection submission action
     */
    comment?: string;
    /**
     * The date created for the collection submission action
     */
    dateCreated?: Date;
    /**
     * The date modified for the collection submission action
     */
    dateModified?: Date;
    /**
     * The actionTrigger determines the trigger used to affect the project
     */
    actionTrigger: CollectionSubmissionActionTrigger;
}

/**
 * MirageCollectionSubmission
 *
 * @description Used to extend the CollectionSubmission model to provide
 * additional functionality for automatically building the collection
 * submission action
 */
export interface MirageCollectionSubmission extends CollectionSubmission {
    submissionAction: MirageSubmissionAction;
    collectionId: string;
}

export default Factory.extend<MirageCollectionSubmission>({
    id: guid('collection-submission'),
    afterCreate(collectionSubmission, server) {
        guidAfterCreate(collectionSubmission, server);
        if (!collectionSubmission.reviewsState) {
            const reviewsState = CollectionSubmissionReviewStates.Accepted;
            collectionSubmission.update({ reviewsState});
        }
        if (!collectionSubmission.collectedType) {
            const collectedType = faker.random.arrayElement(collectionSubmission.collection.collectedTypeChoices);
            collectionSubmission.update({ collectedType });
        }
        if (!collectionSubmission.issue) {
            const issue = faker.random.arrayElement(collectionSubmission.collection.issueChoices);
            collectionSubmission.update({ issue });
        }
        if (!collectionSubmission.programArea) {
            const programArea = faker.random.arrayElement(collectionSubmission.collection.programAreaChoices);
            collectionSubmission.update({ programArea });
        }
        if (!collectionSubmission.status) {
            const status = faker.random.arrayElement(collectionSubmission.collection.statusChoices);
            collectionSubmission.update({ status });
        }
        if (!collectionSubmission.volume) {
            const volume = faker.random.arrayElement(collectionSubmission.collection.volumeChoices);
            collectionSubmission.update({ volume });
        }
        if (!collectionSubmission.studyDesign) {
            const studyDesign = faker.random.arrayElement(collectionSubmission.collection.studyDesignChoices);
            collectionSubmission.update({ studyDesign });
        }
        if (!collectionSubmission.schoolType) {
            const schoolType = faker.random.arrayElement(collectionSubmission.collection.schoolTypeChoices);
            collectionSubmission.update({ schoolType });
        }
        /**
         * Autogenerate the necessary collection submission action business
         * logic
         */
        server.create('collection-submission-action', {
            actionTrigger: CollectionSubmissionActionTrigger.Accept,
            target: collectionSubmission,
            reviewsState: collectionSubmission.reviewsState,
            comment: collectionSubmission.submissionAction?.comment,
            dateCreated: collectionSubmission.submissionAction?.dateCreated,
            dateModified: collectionSubmission.submissionAction?.dateModified,
            isAutogenerated: true,
            creator: server.schema.roots.first().currentUser as ModelInstance<UserModel>,
        });
    },
});

declare module 'ember-cli-mirage/types/registries/model' {
    export default interface MirageModelRegistry {
        'collection-submission': MirageCollectionSubmission;
    } // eslint-disable-line semi
}

declare module 'ember-cli-mirage/types/registries/schema' {
    export default interface MirageSchemaRegistry {
        collectionSubmissions: MirageCollectionSubmission;
    } // eslint-disable-line semi
}
