export default {
    local: {
        url: 'http://localhost:5000/',
        apiUrl: 'http://localhost:8000',
        renderUrl: 'http://localhost:7778/render',
        waterbutlerUrl: 'http://localhost:7777/',
        helpUrl: 'http://localhost:4200/help',
        cookieLoginUrl: 'http://localhost:8080/login',
        oauthUrl: 'http://localhost:8080/oauth2/profile',
        shareBaseUrl: 'https://staging-share.osf.io/',
        shareApiUrl: 'https://staging-share.osf.io/api/v2',
        shareSearchUrl: 'https://staging-share.osf.io/api/v2/search/creativeworks/_search',
    },
    stage: {
        url: 'https://staging.osf.io/',
        apiUrl: 'https://staging-api.osf.io',
        renderUrl: 'https://staging-mfr.osf.io/render',
        waterbutlerUrl: 'https://staging-files.osf.io/',
        helpUrl: 'http://help.osf.io',
        cookieLoginUrl: 'https://staging-accounts.osf.io/login',
        oauthUrl: 'https://staging-accounts.osf.io/oauth2/authorize',
        shareBaseUrl: 'https://staging-share.osf.io/',
        shareApiUrl: 'https://staging-share.osf.io/api/v2',
        shareSearchUrl: 'https://staging-share.osf.io/api/v2/search/creativeworks/_search',
    },
    stage2: {
        url: 'https://staging2.osf.io/',
        apiUrl: 'https://staging2-api.osf.io',
        renderUrl: 'https://staging2-mfr.osf.io/render',
        waterbutlerUrl: 'https://staging2-files.osf.io/',
        helpUrl: 'http://help.osf.io',
        cookieLoginUrl: 'https://staging2-accounts.osf.io/login',
        oauthUrl: 'https://staging2-accounts.osf.io/oauth2/authorize',
        shareBaseUrl: 'https://staging-share.osf.io/',
        shareApiUrl: 'https://staging-share.osf.io/api/v2',
        shareSearchUrl: 'https://staging-share.osf.io/api/v2/search/creativeworks/_search',
    },
    stage3: {
        url: 'https://staging3.osf.io/',
        apiUrl: 'https://staging3-api.osf.io',
        renderUrl: 'https://staging3-mfr.osf.io/render',
        waterbutlerUrl: 'https://staging3-files.osf.io/',
        helpUrl: 'http://help.osf.io',
        cookieLoginUrl: 'https://staging3-accounts.osf.io/login',
        oauthUrl: 'https://staging3-accounts.osf.io/oauth2/authorize',
        shareBaseUrl: 'https://staging-share.osf.io/',
        shareApiUrl: 'https://staging-share.osf.io/api/v2',
        shareSearchUrl: 'https://staging-share.osf.io/api/v2/search/creativeworks/_search',
    },
    prod: {
        url: 'https://osf.io/',
        apiUrl: 'https://api.osf.io',
        renderUrl: 'https://mfr.osf.io/render',
        waterbutlerUrl: 'https://files.osf.io/',
        helpUrl: 'http://help.osf.io',
        cookieLoginUrl: 'https://accounts.osf.io/login',
        oauthUrl: 'https://accounts.osf.io/oauth2/authorize',
        shareBaseUrl: 'https://share.osf.io/',
        shareApiUrl: 'https://share.osf.io/api/v2',
        shareSearchUrl: 'https://share.osf.io/api/v2/search/creativeworks/_search',
    },
    test: {
        url: 'https://test.osf.io/',
        apiUrl: 'https://test-api.osf.io',
        renderUrl: 'https://test-mfr.osf.io/render',
        waterbutlerUrl: 'https://test-files.osf.io/',
        helpUrl: 'http://help.osf.io',
        cookieLoginUrl: 'https://test-accounts.osf.io/login',
        oauthUrl: 'https://test-accounts.osf.io/oauth2/authorize',
        shareBaseUrl: 'https://staging-share.osf.io/',
        shareApiUrl: 'https://staging-share.osf.io/api/v2',
        shareSearchUrl: 'https://staging-share.osf.io/api/v2/search/creativeworks/_search',
    },
    env: {
        url: 'OSF_URL',
        apiUrl: 'OSF_API_URL',
        renderUrl: 'OSF_RENDER_URL',
        waterbutlerUrl: 'OSF_FILE_URL',
        helpUrl: 'OSF_HELP_URL',
        cookieLoginUrl: 'OSF_COOKIE_LOGIN_URL',
        oauthUrl: 'OSF_OAUTH_URL',
        shareBaseUrl: 'SHARE_BASE_URL',
        shareApiUrl: 'SHARE_API_URL',
        shareSearchUrl: 'SHARE_SEARCH_URL',
    },
};
