import CedarMetadataTemplateModel from 'ember-osf-web/models/cedar-metadata-template';


const cedarMetadataTemplates: Array<Partial<CedarMetadataTemplateModel>> = [
    {
        id: '2',
        schemaName: 'Biosample submission template schema',
        cedarId: 'https://repo.metadatacenter.net/templates/58098c2d-dea9-4ec6-8f5d-d85d5f1b4f6f',
        active: true,
        template: Object({
            description: 'Biosample submission template schema generated by the CEDAR Template Editor 2.6.44',
        }),
        templateVersion: 1,
    },
    {
        id: '3',
        schemaName: 'Ffis funder draft template schema',
        cedarId: 'https://repo.metadatacenter.org/templates/352a29d7-3df8-4bdd-bd75-e09d16c7063d',
        active: true,
        template: Object({
            description: 'Ffis funder draft template schema generated by the CEDAR Template Editor 2.6.44',
        }),
        templateVersion: 1,
    },
    {
        id: '1',
        schemaName: 'License field schema',
        cedarId: 'https://repo.metadatacenter.org/template-fields/8b51634a-42df-414b-be27-6cfdfb611591',
        active: true,
        template: Object({
            description: 'License field schema generated by the CEDAR Template Editor 2.4.10',
        }),
        templateVersion: 1,
    },
];

export default cedarMetadataTemplates as CedarMetadataTemplateModel[];
