/* eslint-disable max-len */
export const bibframeTemplate = Object({
    'bibo:status': 'bibo:draft',
    _ui: {
        order: [
            'Title',
            'Variant Title For The Work',
            'Date Of Work',
            'Place Of Origin Of The Work',
            'Nature Of Content',
            'Coverage Of Content',
            'Content Type',
            'Media Type',
            'Carrier Type',
            'captureInformation',
            'Language Of Expression',
            'Genre',
            'Contributor',
            'Copyright Date',
        ],
        pages: [],
        propertyLabels: {
            captureInformation: 'Capture Information',
            Title: 'Title',
            'Place Of Origin Of The Work': 'Place Of Origin Of The Work',
            'Nature Of Content': 'Nature Of Content',
            Contributor: 'Contributor',
            'Copyright Date': 'Copyright Date',
            'Language Of Expression': 'Language Of Expression',
            'Content Type': 'Content Type',
            'Media Type': 'Media Type',
            'Carrier Type': 'Carrier Type',
            'Variant Title For The Work': 'Variant Title For The Work',
            'Date Of Work': 'Date Of Work',
            Genre: 'Genre',
            'Coverage Of Content': 'Coverage Of Content',
        },
    },
    title: 'Bibframe audio work template schema',
    required: [
        '@context',
        '@id',
        'schema:isBasedOn',
        'schema:name',
        'schema:description',
        'pav:createdOn',
        'pav:createdBy',
        'pav:lastUpdatedOn',
        'oslc:modifiedBy',
        'Date Of Work',
        'captureInformation',
        'Variant Title For The Work',
        'Genre',
        'Nature Of Content',
        'Title',
        'Language Of Expression',
        'Media Type',
        'Copyright Date',
        'Contributor',
        'Content Type',
        'Place Of Origin Of The Work',
        'Coverage Of Content',
        'Carrier Type',
    ],
    'schema:name': 'BIBFRAME AUDIO WORK',
    '@context': {
        'pav:lastUpdatedOn': {
            '@type': 'xsd:dateTime',
        },
        oslc: 'http://open-services.net/ns/core#',
        schema: 'http://schema.org/',
        'pav:createdBy': {
            '@type': '@id',
        },
        xsd: 'http://www.w3.org/2001/XMLSchema#',
        'schema:name': {
            '@type': 'xsd:string',
        },
        'pav:createdOn': {
            '@type': 'xsd:dateTime',
        },
        'oslc:modifiedBy': {
            '@type': '@id',
        },
        bibo: 'http://purl.org/ontology/bibo/',
        'schema:description': {
            '@type': 'xsd:string',
        },
        pav: 'http://purl.org/pav/',
    },
    additionalProperties: false,
    type: 'object',
    'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
    description: 'Bibframe audio work template schema generated by the CEDAR Template Editor 2.6.44',
    'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
    'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
    'pav:createdOn': '2016-09-13T10:01:05-07:00',
    'schema:schemaVersion': '1.6.0',
    '@id': 'https://repo.metadatacenter.net/templates/a87b5cb4-6344-4a43-8fcb-82d400bff2c7',
    'pav:version': '0.0.1',
    'schema:description': 'BIBFRAME Audio Work Template',
    '@type': 'https://schema.metadatacenter.org/core/Template',
    properties: {
        'schema:isBasedOn': {
            type: 'string',
            format: 'uri',
        },
        captureInformation: {
            'bibo:status': 'bibo:draft',
            _ui: {
                order: [
                    'captureInformation',
                    'placeOfCapture',
                    'dateOfCapture(SingleDate)',
                    'dateOfCapture',
                ],
                propertyLabels: {
                    dateOfCapture: 'Date Of Capture',
                    captureInformation: 'Capture Information',
                    'dateOfCapture(SingleDate)': 'Date Of Capture( Single Date)',
                    placeOfCapture: 'Place Of Capture',
                },
            },
            title: 'Capture information element schema',
            required: [
                '@context',
                '@id',
                'dateOfCapture',
                'placeOfCapture',
                'captureInformation',
                'dateOfCapture(SingleDate)',
            ],
            'schema:name': 'Capture Information',
            '@context': {
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'schema:name': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                bibo: 'http://purl.org/ontology/bibo/',
                'schema:description': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Capture information element schema autogenerated by the CEDAR Template Editor',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            'schema:schemaVersion': '1.6.0',
            _valueConstraints: {
                requiredValue: false,
            },
            '@id': 'https://repo.metadatacenter.net/template-elements/bcdb354f-413a-4c00-9d21-bc1ac82b3d4c',
            'pav:version': '0.0.1',
            'schema:description': 'BIBFRAME Capture Information Template Element',
            '@type': 'https://schema.metadatacenter.org/core/TemplateElement',
            properties: {
                dateOfCapture: {
                    _ui: {
                        temporalGranularity: 'day',
                        dateType: 'date-range',
                        inputType: 'temporal',
                    },
                    'schema:name': 'Date Of Capture',
                    title: 'Date Of Capture field schema',
                    'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                    '@context': {
                        'schema:name': {
                            '@type': 'xsd:string',
                        },
                        schema: 'http://schema.org/',
                        'pav:createdBy': {
                            '@type': '@id',
                        },
                        xsd: 'http://www.w3.org/2001/XMLSchema#',
                        'oslc:modifiedBy': {
                            '@type': '@id',
                        },
                        skos: 'http://www.w3.org/2004/02/skos/core#',
                        'pav:lastUpdatedOn': {
                            '@type': 'xsd:dateTime',
                        },
                        oslc: 'http://open-services.net/ns/core#',
                        'skos:prefLabel': {
                            '@type': 'xsd:string',
                        },
                        pav: 'http://purl.org/pav/',
                        'skos:altLabel': {
                            '@type': 'xsd:string',
                        },
                        'schema:description': {
                            '@type': 'xsd:string',
                        },
                        'pav:createdOn': {
                            '@type': 'xsd:dateTime',
                        },
                    },
                    additionalProperties: false,
                    type: 'object',
                    'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                    description: 'Date Of Capture field schema generated by the CEDAR Template Editor 2.6.44',
                    'pav:lastUpdatedOn': '2016-09-13T10:05:07-07:00',
                    '@id': 'https://repo.metadatacenter.net/template-fields/0ae92e10-eb1c-45ef-bdb2-483beebdc22a',
                    _valueConstraints: {
                        temporalType: 'xsd:date',
                        requiredValue: false,
                    },
                    required: [
                        '@value',
                    ],
                    'schema:schemaVersion': '1.6.0',
                    properties: {
                        '@value': {
                            type: [
                                'string',
                                'null',
                            ],
                        },
                        '@type': {
                            oneOf: [
                                {
                                    type: 'string',
                                    format: 'uri',
                                },
                                {
                                    minItems: 1,
                                    type: 'array',
                                    uniqueItems: true,
                                    items: {
                                        type: 'string',
                                        format: 'uri',
                                    },
                                },
                            ],
                        },
                        'rdfs:label': {
                            type: [
                                'string',
                                'null',
                            ],
                        },
                    },
                    'schema:description': '',
                    '@type': 'https://schema.metadatacenter.org/core/TemplateField',
                    'pav:createdOn': '2016-09-13T10:05:07-07:00',
                    $schema: 'http://json-schema.org/draft-04/schema#',
                },
                placeOfCapture: {
                    _ui: {
                        inputType: 'textfield',
                    },
                    'schema:name': 'Place Of Capture',
                    title: 'Place Of Capture field schema',
                    'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                    '@context': {
                        'schema:name': {
                            '@type': 'xsd:string',
                        },
                        schema: 'http://schema.org/',
                        'pav:createdBy': {
                            '@type': '@id',
                        },
                        xsd: 'http://www.w3.org/2001/XMLSchema#',
                        'oslc:modifiedBy': {
                            '@type': '@id',
                        },
                        skos: 'http://www.w3.org/2004/02/skos/core#',
                        'pav:lastUpdatedOn': {
                            '@type': 'xsd:dateTime',
                        },
                        oslc: 'http://open-services.net/ns/core#',
                        'skos:prefLabel': {
                            '@type': 'xsd:string',
                        },
                        pav: 'http://purl.org/pav/',
                        'skos:altLabel': {
                            '@type': 'xsd:string',
                        },
                        'schema:description': {
                            '@type': 'xsd:string',
                        },
                        'pav:createdOn': {
                            '@type': 'xsd:dateTime',
                        },
                    },
                    additionalProperties: false,
                    type: 'object',
                    'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                    description: 'Place Of Capture field schema generated by the CEDAR Template Editor 2.6.44',
                    'pav:lastUpdatedOn': '2016-09-13T10:05:07-07:00',
                    '@id': 'https://repo.metadatacenter.net/template-fields/049288ff-58e4-4d75-9a75-0c455b5e07be',
                    _valueConstraints: {
                        requiredValue: false,
                    },
                    required: [
                        '@value',
                    ],
                    'schema:schemaVersion': '1.6.0',
                    properties: {
                        '@value': {
                            type: [
                                'string',
                                'null',
                            ],
                        },
                        '@type': {
                            oneOf: [
                                {
                                    type: 'string',
                                    format: 'uri',
                                },
                                {
                                    minItems: 1,
                                    type: 'array',
                                    uniqueItems: true,
                                    items: {
                                        type: 'string',
                                        format: 'uri',
                                    },
                                },
                            ],
                        },
                        'rdfs:label': {
                            type: [
                                'string',
                                'null',
                            ],
                        },
                    },
                    'schema:description': '',
                    '@type': 'https://schema.metadatacenter.org/core/TemplateField',
                    'pav:createdOn': '2016-09-13T10:05:07-07:00',
                    $schema: 'http://json-schema.org/draft-04/schema#',
                },
                captureInformation: {
                    _ui: {
                        inputType: 'textfield',
                    },
                    'schema:name': 'Capture Information',
                    title: 'Capture information field schema',
                    'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                    '@context': {
                        'schema:name': {
                            '@type': 'xsd:string',
                        },
                        schema: 'http://schema.org/',
                        'pav:createdBy': {
                            '@type': '@id',
                        },
                        xsd: 'http://www.w3.org/2001/XMLSchema#',
                        'oslc:modifiedBy': {
                            '@type': '@id',
                        },
                        skos: 'http://www.w3.org/2004/02/skos/core#',
                        'pav:lastUpdatedOn': {
                            '@type': 'xsd:dateTime',
                        },
                        oslc: 'http://open-services.net/ns/core#',
                        'skos:prefLabel': {
                            '@type': 'xsd:string',
                        },
                        pav: 'http://purl.org/pav/',
                        'skos:altLabel': {
                            '@type': 'xsd:string',
                        },
                        'schema:description': {
                            '@type': 'xsd:string',
                        },
                        'pav:createdOn': {
                            '@type': 'xsd:dateTime',
                        },
                    },
                    additionalProperties: false,
                    type: 'object',
                    'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                    description: 'Capture information field schema autogenerated by the CEDAR Template Editor',
                    'pav:lastUpdatedOn': '2016-09-13T10:05:07-07:00',
                    '@id': 'https://repo.metadatacenter.net/template-fields/0cb15dd0-c04f-4bcd-b463-91bcdf575eef',
                    _valueConstraints: {
                        requiredValue: false,
                    },
                    required: [
                        '@value',
                    ],
                    'schema:schemaVersion': '1.6.0',
                    properties: {
                        '@value': {
                            type: [
                                'string',
                                'null',
                            ],
                        },
                        '@type': {
                            oneOf: [
                                {
                                    type: 'string',
                                    format: 'uri',
                                },
                                {
                                    minItems: 1,
                                    type: 'array',
                                    uniqueItems: true,
                                    items: {
                                        type: 'string',
                                        format: 'uri',
                                    },
                                },
                            ],
                        },
                        'rdfs:label': {
                            type: [
                                'string',
                                'null',
                            ],
                        },
                    },
                    'schema:description': '',
                    '@type': 'https://schema.metadatacenter.org/core/TemplateField',
                    'pav:createdOn': '2016-09-13T10:05:07-07:00',
                    $schema: 'http://json-schema.org/draft-04/schema#',
                },
                '@id': {
                    type: 'string',
                    format: 'uri',
                },
                '@context': {
                    additionalProperties: false,
                    type: 'object',
                    required: [
                        'captureInformation',
                        'placeOfCapture',
                        'dateOfCapture(SingleDate)',
                        'dateOfCapture',
                    ],
                    properties: {
                        dateOfCapture: {
                            enum: [
                                'https://schema.metadatacenter.net/properties/dateOfCapture',
                            ],
                        },
                        captureInformation: {
                            enum: [
                                'https://schema.metadatacenter.net/properties/captureInformation',
                            ],
                        },
                        'dateOfCapture(SingleDate)': {
                            enum: [
                                'https://schema.metadatacenter.net/properties/dateOfCapture(SingleDate)',
                            ],
                        },
                        placeOfCapture: {
                            enum: [
                                'https://schema.metadatacenter.net/properties/placeOfCapture',
                            ],
                        },
                    },
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'dateOfCapture(SingleDate)': {
                    _ui: {
                        temporalGranularity: 'day',
                        dateType: 'single-date',
                        inputType: 'temporal',
                    },
                    'schema:name': 'Date Of Capture( Single Date)',
                    title: 'Date Of Capture( Single Date) field schema',
                    'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                    '@context': {
                        'schema:name': {
                            '@type': 'xsd:string',
                        },
                        schema: 'http://schema.org/',
                        'pav:createdBy': {
                            '@type': '@id',
                        },
                        xsd: 'http://www.w3.org/2001/XMLSchema#',
                        'oslc:modifiedBy': {
                            '@type': '@id',
                        },
                        skos: 'http://www.w3.org/2004/02/skos/core#',
                        'pav:lastUpdatedOn': {
                            '@type': 'xsd:dateTime',
                        },
                        oslc: 'http://open-services.net/ns/core#',
                        'skos:prefLabel': {
                            '@type': 'xsd:string',
                        },
                        pav: 'http://purl.org/pav/',
                        'skos:altLabel': {
                            '@type': 'xsd:string',
                        },
                        'schema:description': {
                            '@type': 'xsd:string',
                        },
                        'pav:createdOn': {
                            '@type': 'xsd:dateTime',
                        },
                    },
                    additionalProperties: false,
                    type: 'object',
                    'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                    description: 'Date Of Capture( Single Date) field schema generated by the CEDAR Template Editor 2.6.44',
                    'pav:lastUpdatedOn': '2016-09-13T10:05:07-07:00',
                    '@id': 'https://repo.metadatacenter.net/template-fields/3af46ca1-acfe-452a-b9b0-66b6beae54ad',
                    _valueConstraints: {
                        temporalType: 'xsd:date',
                        requiredValue: false,
                    },
                    required: [
                        '@value',
                    ],
                    'schema:schemaVersion': '1.6.0',
                    properties: {
                        '@value': {
                            type: [
                                'string',
                                'null',
                            ],
                        },
                        '@type': {
                            oneOf: [
                                {
                                    type: 'string',
                                    format: 'uri',
                                },
                                {
                                    minItems: 1,
                                    type: 'array',
                                    uniqueItems: true,
                                    items: {
                                        type: 'string',
                                        format: 'uri',
                                    },
                                },
                            ],
                        },
                        'rdfs:label': {
                            type: [
                                'string',
                                'null',
                            ],
                        },
                    },
                    'schema:description': '',
                    '@type': 'https://schema.metadatacenter.org/core/TemplateField',
                    'pav:createdOn': '2016-09-13T10:05:07-07:00',
                    $schema: 'http://json-schema.org/draft-04/schema#',
                },
            },
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'schema:description': {
            type: 'string',
        },
        '@type': {
            oneOf: [
                {
                    type: 'string',
                    format: 'uri',
                },
                {
                    minItems: 1,
                    type: 'array',
                    uniqueItems: true,
                    items: {
                        type: 'string',
                        format: 'uri',
                    },
                },
            ],
        },
        'schema:name': {
            type: 'string',
            minLength: 1,
        },
        'pav:createdBy': {
            type: [
                'string',
                'null',
            ],
            format: 'uri',
        },
        'oslc:modifiedBy': {
            type: [
                'string',
                'null',
            ],
            format: 'uri',
        },
        'pav:lastUpdatedOn': {
            type: [
                'string',
                'null',
            ],
            format: 'date-time',
        },
        '@context': {
            additionalProperties: false,
            type: 'object',
            required: [
                'xsd',
                'rdfs',
                'pav',
                'schema',
                'oslc',
                'Title',
                'Variant Title For The Work',
                'Date Of Work',
                'Place Of Origin Of The Work',
                'Nature Of Content',
                'Coverage Of Content',
                'Content Type',
                'Media Type',
                'Carrier Type',
                'Language Of Expression',
                'Genre',
                'Contributor',
                'Copyright Date',
                'captureInformation',
                'schema:isBasedOn',
                'schema:description',
                'schema:name',
                'rdfs:label',
                'oslc:modifiedBy',
                'pav:createdBy',
                'pav:createdOn',
                'pav:lastUpdatedOn',
                'skos',
                'skos:notation',
            ],
            properties: {
                'rdfs:label': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                'xsd:string',
                            ],
                            type: 'string',
                        },
                    },
                },
                rdfs: {
                    enum: [
                        'http://www.w3.org/2000/01/rdf-schema#',
                    ],
                    type: 'string',
                    format: 'uri',
                },
                oslc: {
                    enum: [
                        'http://open-services.net/ns/core#',
                    ],
                    type: 'string',
                    format: 'uri',
                },
                captureInformation: {
                    enum: [
                        'https://schema.metadatacenter.net/properties/captureInformation',
                    ],
                },
                skos: {
                    enum: [
                        'http://www.w3.org/2004/02/skos/core#',
                    ],
                    type: 'string',
                    format: 'uri',
                },
                'oslc:modifiedBy': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                '@id',
                            ],
                            type: 'string',
                        },
                    },
                },
                'schema:description': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                'xsd:string',
                            ],
                            type: 'string',
                        },
                    },
                },
                'pav:createdBy': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                '@id',
                            ],
                            type: 'string',
                        },
                    },
                },
                'schema:isBasedOn': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                '@id',
                            ],
                            type: 'string',
                        },
                    },
                },
                'schema:name': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                'xsd:string',
                            ],
                            type: 'string',
                        },
                    },
                },
                schema: {
                    enum: [
                        'http://schema.org/',
                    ],
                    type: 'string',
                    format: 'uri',
                },
                pav: {
                    enum: [
                        'http://purl.org/pav/',
                    ],
                    type: 'string',
                    format: 'uri',
                },
                xsd: {
                    enum: [
                        'http://www.w3.org/2001/XMLSchema#',
                    ],
                    type: 'string',
                    format: 'uri',
                },
                'pav:lastUpdatedOn': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                'xsd:dateTime',
                            ],
                            type: 'string',
                        },
                    },
                },
                'pav:createdOn': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                'xsd:dateTime',
                            ],
                            type: 'string',
                        },
                    },
                },
                'skos:notation': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                'xsd:string',
                            ],
                            type: 'string',
                        },
                    },
                },
                'pav:derivedFrom': {
                    type: 'object',
                    properties: {
                        '@type': {
                            enum: [
                                '@id',
                            ],
                            type: 'string',
                        },
                    },
                },
                Title: {
                    enum: [
                        'https://schema.metadatacenter.net/properties/title',
                    ],
                },
                'Place Of Origin Of The Work': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/placeOfOriginOfTheWork',
                    ],
                },
                'Nature Of Content': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/natureOfContent',
                    ],
                },
                Contributor: {
                    enum: [
                        'https://schema.metadatacenter.net/properties/contributor',
                    ],
                },
                'Copyright Date': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/copyrightDate',
                    ],
                },
                'Language Of Expression': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/languageOfExpression',
                    ],
                },
                'Content Type': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/contentType',
                    ],
                },
                'Media Type': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/mediaType',
                    ],
                },
                'Carrier Type': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/carrierType',
                    ],
                },
                'Variant Title For The Work': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/variantTitleForTheWork',
                    ],
                },
                'Date Of Work': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/dateOfWork',
                    ],
                },
                Genre: {
                    enum: [
                        'https://schema.metadatacenter.net/properties/genre',
                    ],
                },
                'Coverage Of Content': {
                    enum: [
                        'https://schema.metadatacenter.net/properties/coverageOfContent',
                    ],
                },
            },
        },
        '@id': {
            type: [
                'string',
                'null',
            ],
            format: 'uri',
        },
        'pav:derivedFrom': {
            type: 'string',
            format: 'uri',
        },
        'pav:createdOn': {
            type: [
                'string',
                'null',
            ],
            format: 'date-time',
        },
        Title: {
            minItems: 1,
            type: 'array',
            items: {
                _ui: {
                    inputType: 'textfield',
                },
                'schema:name': 'Title',
                title: 'Title field schema',
                'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                '@context': {
                    'schema:name': {
                        '@type': 'xsd:string',
                    },
                    schema: 'http://schema.org/',
                    'pav:createdBy': {
                        '@type': '@id',
                    },
                    xsd: 'http://www.w3.org/2001/XMLSchema#',
                    'oslc:modifiedBy': {
                        '@type': '@id',
                    },
                    skos: 'http://www.w3.org/2004/02/skos/core#',
                    'pav:lastUpdatedOn': {
                        '@type': 'xsd:dateTime',
                    },
                    oslc: 'http://open-services.net/ns/core#',
                    'skos:prefLabel': {
                        '@type': 'xsd:string',
                    },
                    pav: 'http://purl.org/pav/',
                    'skos:altLabel': {
                        '@type': 'xsd:string',
                    },
                    'schema:description': {
                        '@type': 'xsd:string',
                    },
                    'pav:createdOn': {
                        '@type': 'xsd:dateTime',
                    },
                },
                additionalProperties: false,
                type: 'object',
                'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                description: 'Title field schema autogenerated by the CEDAR Template Editor',
                'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
                '@id': 'https://repo.metadatacenter.net/template-fields/1c696f77-7116-4284-a429-bbc67b32531d',
                _valueConstraints: {
                    requiredValue: false,
                },
                required: [
                    '@value',
                ],
                'schema:schemaVersion': '1.6.0',
                properties: {
                    '@value': {
                        type: [
                            'string',
                            'null',
                        ],
                    },
                    '@type': {
                        oneOf: [
                            {
                                type: 'string',
                                format: 'uri',
                            },
                            {
                                minItems: 1,
                                type: 'array',
                                uniqueItems: true,
                                items: {
                                    type: 'string',
                                    format: 'uri',
                                },
                            },
                        ],
                    },
                    'rdfs:label': {
                        type: [
                            'string',
                            'null',
                        ],
                    },
                },
                'schema:description': '',
                '@type': 'https://schema.metadatacenter.org/core/TemplateField',
                'pav:createdOn': '2016-09-13T10:05:35-07:00',
                $schema: 'http://json-schema.org/draft-04/schema#',
            },
        },
        'Place Of Origin Of The Work': {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Place Of Origin Of The Work',
            title: 'Place Of Origin Of The Work field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Place Of Origin Of The Work field schema generated by the CEDAR Template Editor 2.6.44',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/c57ee2e9-42b1-4227-9733-947483ed6fdc',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'Nature Of Content': {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Nature Of Content',
            title: 'Nature Of Content field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Nature Of Content field schema generated by the CEDAR Template Editor 2.6.44',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/67c13404-ef6e-4d43-b027-f064fe1e98d6',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        Contributor: {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Contributor',
            title: 'Contributor field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Contributor field schema autogenerated by the CEDAR Template Editor',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/4c190d27-a94d-4db6-8639-e56c3506a437',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'Copyright Date': {
            _ui: {
                temporalGranularity: 'day',
                dateType: 'single-date',
                inputType: 'temporal',
            },
            'schema:name': 'Copyright Date',
            title: 'Copyright Date field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Copyright Date field schema generated by the CEDAR Template Editor 2.6.44',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/de1dffb5-8918-4bfa-ba08-4cd8a5bcd4a8',
            _valueConstraints: {
                temporalType: 'xsd:date',
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'Language Of Expression': {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Language Of Expression',
            title: 'Language Of Expression field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Language Of Expression field schema generated by the CEDAR Template Editor 2.6.44',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/c7e518b1-6524-43fc-80cd-778e19620a36',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'Content Type': {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Content Type',
            title: 'Content type field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Content type field schema autogenerated by the CEDAR Template Editor',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/abcc37f2-e62f-45cc-be83-b58350d66a62',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'Media Type': {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Media Type',
            title: 'Media type field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Media type field schema autogenerated by the CEDAR Template Editor',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/6fd2e261-219b-4a9b-b0b6-817c1be1be18',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'Carrier Type': {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Carrier Type',
            title: 'Carrier type field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Carrier type field schema autogenerated by the CEDAR Template Editor',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/3cf2192f-279e-403c-a3f0-405b4231c370',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'Variant Title For The Work': {
            minItems: 1,
            type: 'array',
            items: {
                _ui: {
                    inputType: 'textfield',
                },
                'schema:name': 'Variant Title For The Work',
                title: 'Variant Title For The Work field schema',
                'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                '@context': {
                    'schema:name': {
                        '@type': 'xsd:string',
                    },
                    schema: 'http://schema.org/',
                    'pav:createdBy': {
                        '@type': '@id',
                    },
                    xsd: 'http://www.w3.org/2001/XMLSchema#',
                    'oslc:modifiedBy': {
                        '@type': '@id',
                    },
                    skos: 'http://www.w3.org/2004/02/skos/core#',
                    'pav:lastUpdatedOn': {
                        '@type': 'xsd:dateTime',
                    },
                    oslc: 'http://open-services.net/ns/core#',
                    'skos:prefLabel': {
                        '@type': 'xsd:string',
                    },
                    pav: 'http://purl.org/pav/',
                    'skos:altLabel': {
                        '@type': 'xsd:string',
                    },
                    'schema:description': {
                        '@type': 'xsd:string',
                    },
                    'pav:createdOn': {
                        '@type': 'xsd:dateTime',
                    },
                },
                additionalProperties: false,
                type: 'object',
                'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
                description: 'Variant Title For The Work field schema generated by the CEDAR Template Editor 2.6.44',
                'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
                '@id': 'https://repo.metadatacenter.net/template-fields/736f4871-d824-4057-9e38-f4650a9cb56b',
                _valueConstraints: {
                    requiredValue: false,
                },
                required: [
                    '@value',
                ],
                'schema:schemaVersion': '1.6.0',
                properties: {
                    '@value': {
                        type: [
                            'string',
                            'null',
                        ],
                    },
                    '@type': {
                        oneOf: [
                            {
                                type: 'string',
                                format: 'uri',
                            },
                            {
                                minItems: 1,
                                type: 'array',
                                uniqueItems: true,
                                items: {
                                    type: 'string',
                                    format: 'uri',
                                },
                            },
                        ],
                    },
                    'rdfs:label': {
                        type: [
                            'string',
                            'null',
                        ],
                    },
                },
                'schema:description': '',
                '@type': 'https://schema.metadatacenter.org/core/TemplateField',
                'pav:createdOn': '2016-09-13T10:05:35-07:00',
                $schema: 'http://json-schema.org/draft-04/schema#',
            },
        },
        'Date Of Work': {
            _ui: {
                temporalGranularity: 'day',
                dateType: 'single-date',
                inputType: 'temporal',
            },
            'schema:name': 'Date Of Work',
            title: 'Date Of Work field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Date Of Work field schema generated by the CEDAR Template Editor 2.6.44',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/3ab9df03-5a55-4484-bc10-b5a4a3acca31',
            _valueConstraints: {
                temporalType: 'xsd:date',
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        Genre: {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Genre',
            title: 'Genre field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Genre field schema autogenerated by the CEDAR Template Editor',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/f8476717-a1b4-4c1a-9666-531539f95419',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        'Coverage Of Content': {
            _ui: {
                inputType: 'textfield',
            },
            'schema:name': 'Coverage Of Content',
            title: 'Coverage Of Content field schema',
            'pav:createdBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            '@context': {
                'schema:name': {
                    '@type': 'xsd:string',
                },
                schema: 'http://schema.org/',
                'pav:createdBy': {
                    '@type': '@id',
                },
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                oslc: 'http://open-services.net/ns/core#',
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                pav: 'http://purl.org/pav/',
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
            },
            additionalProperties: false,
            type: 'object',
            'oslc:modifiedBy': 'https://repo.metadatacenter.net/users/6d21a887-b704-49a9-922a-aa71632f3232',
            description: 'Coverage Of Content field schema generated by the CEDAR Template Editor 2.6.44',
            'pav:lastUpdatedOn': '2016-09-13T10:05:35-07:00',
            '@id': 'https://repo.metadatacenter.net/template-fields/6214d1f3-9667-492c-9d87-8ce5e7b65960',
            _valueConstraints: {
                requiredValue: false,
            },
            required: [
                '@value',
            ],
            'schema:schemaVersion': '1.6.0',
            properties: {
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            minItems: 1,
                            type: 'array',
                            uniqueItems: true,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            'schema:description': '',
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            'pav:createdOn': '2016-09-13T10:05:35-07:00',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
    },
    $schema: 'http://json-schema.org/draft-04/schema#',
});
