/* eslint-disable max-len */
export const testingTemplate = Object({
    '@id': 'https://repo.metadatacenter.org/templates/3900b140-a27c-4fca-8a00-c1ccb0f3647f',
    '@type': 'https://schema.metadatacenter.org/core/Template',
    '@context': {
        xsd: 'http://www.w3.org/2001/XMLSchema#',
        pav: 'http://purl.org/pav/',
        bibo: 'http://purl.org/ontology/bibo/',
        oslc: 'http://open-services.net/ns/core#',
        schema: 'http://schema.org/',
        'schema:name': {
            '@type': 'xsd:string',
        },
        'schema:description': {
            '@type': 'xsd:string',
        },
        'pav:createdOn': {
            '@type': 'xsd:dateTime',
        },
        'pav:createdBy': {
            '@type': '@id',
        },
        'pav:lastUpdatedOn': {
            '@type': 'xsd:dateTime',
        },
        'oslc:modifiedBy': {
            '@type': '@id',
        },
    },
    type: 'object',
    title: 'Data catalog template schema',
    description: 'Data catalog template schema generated by the CEDAR Template Editor 2.6.49',
    _ui: {
        pages: [],
        order: [
            'catalogTitle',
            'catalogDescription',
            'publisher',
            'datasetIdentifier',
            'catalogIdentifier',
        ],
        propertyLabels: {
            catalogTitle: 'catalogTitle',
            catalogDescription: 'catalogDescription',
            datasetIdentifier: 'datasetIdentifier',
            publisher: 'publisher',
            catalogIdentifier: 'catalogIdentifier',
        },
        propertyDescriptions: {
            catalogTitle: 'The title of data catalog. A data catalog represents a curated collection of metadata about datasets.',
            catalogDescription: 'A free-text description of the data catalog item.',
            datasetIdentifier: 'Globally unique, persistent and resolvable identifier that identifies datasets that are part of the data catalog being described.',
            publisher: 'Globally unique, persistent and resolvable identifier of the entity that holds, archives, publishes prints, distributes, releases, issues, or produces the catalog being described.',
            catalogIdentifier: 'Globally unique, persistent and resolvable identifier that identifies data catalogs that are part of the data catalog being described.',
        },
    },
    properties: {
        '@context': {
            type: 'object',
            properties: {
                rdfs: {
                    type: 'string',
                    format: 'uri',
                    enum: [
                        'http://www.w3.org/2000/01/rdf-schema#',
                    ],
                },
                xsd: {
                    type: 'string',
                    format: 'uri',
                    enum: [
                        'http://www.w3.org/2001/XMLSchema#',
                    ],
                },
                pav: {
                    type: 'string',
                    format: 'uri',
                    enum: [
                        'http://purl.org/pav/',
                    ],
                },
                schema: {
                    type: 'string',
                    format: 'uri',
                    enum: [
                        'http://schema.org/',
                    ],
                },
                oslc: {
                    type: 'string',
                    format: 'uri',
                    enum: [
                        'http://open-services.net/ns/core#',
                    ],
                },
                skos: {
                    type: 'string',
                    format: 'uri',
                    enum: [
                        'http://www.w3.org/2004/02/skos/core#',
                    ],
                },
                'rdfs:label': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                'xsd:string',
                            ],
                        },
                    },
                },
                'schema:isBasedOn': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                '@id',
                            ],
                        },
                    },
                },
                'schema:name': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                'xsd:string',
                            ],
                        },
                    },
                },
                'schema:description': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                'xsd:string',
                            ],
                        },
                    },
                },
                'pav:derivedFrom': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                '@id',
                            ],
                        },
                    },
                },
                'pav:createdOn': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                'xsd:dateTime',
                            ],
                        },
                    },
                },
                'pav:createdBy': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                '@id',
                            ],
                        },
                    },
                },
                'pav:lastUpdatedOn': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                'xsd:dateTime',
                            ],
                        },
                    },
                },
                'oslc:modifiedBy': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                '@id',
                            ],
                        },
                    },
                },
                'skos:notation': {
                    type: 'object',
                    properties: {
                        '@type': {
                            type: 'string',
                            enum: [
                                'xsd:string',
                            ],
                        },
                    },
                },
                catalogTitle: {
                    enum: [
                        'http://purl.org/dc/terms/title',
                    ],
                },
                catalogDescription: {
                    enum: [
                        'http://purl.org/dc/terms/description',
                    ],
                },
                datasetIdentifier: {
                    enum: [
                        'http://www.w3.org/ns/dcat#dataset',
                    ],
                },
                publisher: {
                    enum: [
                        'https://schema.metadatacenter.org/properties/692e6014-f507-4d4a-8f5f-112ae8d3edb4',
                    ],
                },
                catalogIdentifier: {
                    enum: [
                        'https://schema.metadatacenter.org/properties/4191b152-a77d-4cf8-afb0-04301031a983',
                    ],
                },
            },
            required: [
                'xsd',
                'pav',
                'schema',
                'oslc',
                'schema:isBasedOn',
                'schema:name',
                'schema:description',
                'pav:createdOn',
                'pav:createdBy',
                'pav:lastUpdatedOn',
                'oslc:modifiedBy',
            ],
            additionalProperties: false,
        },
        '@id': {
            type: [
                'string',
                'null',
            ],
            format: 'uri',
        },
        '@type': {
            oneOf: [
                {
                    type: 'string',
                    format: 'uri',
                },
                {
                    type: 'array',
                    minItems: 1,
                    items: {
                        type: 'string',
                        format: 'uri',
                    },
                    uniqueItems: true,
                },
            ],
        },
        'schema:isBasedOn': {
            type: 'string',
            format: 'uri',
        },
        'schema:name': {
            type: 'string',
            minLength: 1,
        },
        'schema:description': {
            type: 'string',
        },
        'pav:derivedFrom': {
            type: 'string',
            format: 'uri',
        },
        'pav:createdOn': {
            type: [
                'string',
                'null',
            ],
            format: 'date-time',
        },
        'pav:createdBy': {
            type: [
                'string',
                'null',
            ],
            format: 'uri',
        },
        'pav:lastUpdatedOn': {
            type: [
                'string',
                'null',
            ],
            format: 'date-time',
        },
        'oslc:modifiedBy': {
            type: [
                'string',
                'null',
            ],
            format: 'uri',
        },
        catalogTitle: {
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            '@context': {
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                pav: 'http://purl.org/pav/',
                bibo: 'http://purl.org/ontology/bibo/',
                oslc: 'http://open-services.net/ns/core#',
                schema: 'http://schema.org/',
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'schema:name': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
                'pav:createdBy': {
                    '@type': '@id',
                },
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
            },
            type: 'object',
            title: 'catalogTitle field schema',
            description: 'catalogTitle field schema generated by the CEDAR Template Editor 2.6.0',
            _ui: {
                inputType: 'textfield',
            },
            _valueConstraints: {
                requiredValue: true,
            },
            properties: {
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            type: 'array',
                            minItems: 1,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                            uniqueItems: true,
                        },
                    ],
                },
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            required: [
                '@value',
            ],
            'schema:name': 'catalogTitle',
            'schema:description': 'The title of data catalog. A data catalog represents a curated collection of metadata about datasets.',
            'pav:createdOn': '2022-02-01T11:19:21-08:00',
            'pav:createdBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
            'pav:lastUpdatedOn': '2022-02-01T11:19:21-08:00',
            'oslc:modifiedBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
            'schema:schemaVersion': '1.6.0',
            additionalProperties: false,
            'skos:prefLabel': 'Catalog Title',
            '@id': 'https://repo.metadatacenter.org/template-fields/2b0906ae-2761-4a4c-b85c-78c9275426f6',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        catalogDescription: {
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            '@context': {
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                pav: 'http://purl.org/pav/',
                bibo: 'http://purl.org/ontology/bibo/',
                oslc: 'http://open-services.net/ns/core#',
                schema: 'http://schema.org/',
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'schema:name': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
                'pav:createdBy': {
                    '@type': '@id',
                },
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
            },
            type: 'object',
            title: 'catalogDescription field schema',
            description: 'catalogDescription field schema generated by the CEDAR Template Editor 2.6.0',
            _ui: {
                inputType: 'textfield',
            },
            _valueConstraints: {
                requiredValue: false,
            },
            properties: {
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            type: 'array',
                            minItems: 1,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                            uniqueItems: true,
                        },
                    ],
                },
                '@value': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
            },
            required: [
                '@value',
            ],
            'schema:name': 'catalogDescription',
            'schema:description': 'A free-text description of the data catalog item.',
            'pav:createdOn': '2022-02-01T11:19:21-08:00',
            'pav:createdBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
            'pav:lastUpdatedOn': '2022-02-01T11:19:21-08:00',
            'oslc:modifiedBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
            'schema:schemaVersion': '1.6.0',
            additionalProperties: false,
            'skos:prefLabel': 'Catalog Description',
            '@id': 'https://repo.metadatacenter.org/template-fields/2a3a851f-2e9c-4b22-8923-4f24c6bd977e',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        datasetIdentifier: {
            type: 'array',
            minItems: 1,
            items: {
                type: 'object',
                '@type': 'https://schema.metadatacenter.org/core/TemplateField',
                '@context': {
                    xsd: 'http://www.w3.org/2001/XMLSchema#',
                    pav: 'http://purl.org/pav/',
                    bibo: 'http://purl.org/ontology/bibo/',
                    oslc: 'http://open-services.net/ns/core#',
                    schema: 'http://schema.org/',
                    skos: 'http://www.w3.org/2004/02/skos/core#',
                    'schema:name': {
                        '@type': 'xsd:string',
                    },
                    'schema:description': {
                        '@type': 'xsd:string',
                    },
                    'skos:prefLabel': {
                        '@type': 'xsd:string',
                    },
                    'skos:altLabel': {
                        '@type': 'xsd:string',
                    },
                    'pav:createdOn': {
                        '@type': 'xsd:dateTime',
                    },
                    'pav:createdBy': {
                        '@type': '@id',
                    },
                    'pav:lastUpdatedOn': {
                        '@type': 'xsd:dateTime',
                    },
                    'oslc:modifiedBy': {
                        '@type': '@id',
                    },
                },
                title: 'datasetIdentifier field schema',
                description: 'datasetIdentifier field schema generated by the CEDAR Template Editor 2.6.0',
                _ui: {
                    inputType: 'link',
                },
                _valueConstraints: {
                    requiredValue: false,
                },
                properties: {
                    '@type': {
                        oneOf: [
                            {
                                type: 'string',
                                format: 'uri',
                            },
                            {
                                type: 'array',
                                minItems: 1,
                                items: {
                                    type: 'string',
                                    format: 'uri',
                                },
                                uniqueItems: true,
                            },
                        ],
                    },
                    'rdfs:label': {
                        type: [
                            'string',
                            'null',
                        ],
                    },
                    '@id': {
                        type: 'string',
                        format: 'uri',
                    },
                },
                additionalProperties: false,
                'pav:createdOn': '2022-02-01T11:19:21-08:00',
                'pav:createdBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
                'pav:lastUpdatedOn': '2022-02-01T11:19:21-08:00',
                'oslc:modifiedBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
                'schema:schemaVersion': '1.6.0',
                'schema:name': 'datasetIdentifier',
                'schema:description': 'Globally unique, persistent and resolvable identifier that identifies datasets that are part of the data catalog being described.',
                'skos:prefLabel': 'Dataset Identifier',
                '@id': 'https://repo.metadatacenter.org/template-fields/c72c114b-7b44-4e29-884f-322406de06fe',
                $schema: 'http://json-schema.org/draft-04/schema#',
            },
        },
        publisher: {
            '@type': 'https://schema.metadatacenter.org/core/TemplateField',
            '@context': {
                xsd: 'http://www.w3.org/2001/XMLSchema#',
                pav: 'http://purl.org/pav/',
                bibo: 'http://purl.org/ontology/bibo/',
                oslc: 'http://open-services.net/ns/core#',
                schema: 'http://schema.org/',
                skos: 'http://www.w3.org/2004/02/skos/core#',
                'schema:name': {
                    '@type': 'xsd:string',
                },
                'schema:description': {
                    '@type': 'xsd:string',
                },
                'skos:prefLabel': {
                    '@type': 'xsd:string',
                },
                'skos:altLabel': {
                    '@type': 'xsd:string',
                },
                'pav:createdOn': {
                    '@type': 'xsd:dateTime',
                },
                'pav:createdBy': {
                    '@type': '@id',
                },
                'pav:lastUpdatedOn': {
                    '@type': 'xsd:dateTime',
                },
                'oslc:modifiedBy': {
                    '@type': '@id',
                },
            },
            type: 'object',
            title: 'publisher field schema',
            description: 'publisher field schema generated by the CEDAR Template Editor 2.6.0',
            _ui: {
                inputType: 'link',
            },
            _valueConstraints: {
                requiredValue: false,
            },
            properties: {
                '@type': {
                    oneOf: [
                        {
                            type: 'string',
                            format: 'uri',
                        },
                        {
                            type: 'array',
                            minItems: 1,
                            items: {
                                type: 'string',
                                format: 'uri',
                            },
                            uniqueItems: true,
                        },
                    ],
                },
                'rdfs:label': {
                    type: [
                        'string',
                        'null',
                    ],
                },
                '@id': {
                    type: 'string',
                    format: 'uri',
                },
            },
            'schema:name': 'publisher',
            'schema:description': 'Globally unique, persistent and resolvable identifier of the entity that holds, archives, publishes prints, distributes, releases, issues, or produces the catalog being described.',
            'pav:createdOn': '2022-02-01T11:19:21-08:00',
            'pav:createdBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
            'pav:lastUpdatedOn': '2022-02-01T11:19:21-08:00',
            'oslc:modifiedBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
            'schema:schemaVersion': '1.6.0',
            additionalProperties: false,
            'skos:prefLabel': 'Publisher',
            '@id': 'https://repo.metadatacenter.org/template-fields/64f8b236-9127-41fb-9b2a-dacecfa9ee37',
            $schema: 'http://json-schema.org/draft-04/schema#',
        },
        catalogIdentifier: {
            type: 'array',
            minItems: 1,
            items: {
                type: 'object',
                '@type': 'https://schema.metadatacenter.org/core/TemplateField',
                '@context': {
                    xsd: 'http://www.w3.org/2001/XMLSchema#',
                    pav: 'http://purl.org/pav/',
                    bibo: 'http://purl.org/ontology/bibo/',
                    oslc: 'http://open-services.net/ns/core#',
                    schema: 'http://schema.org/',
                    skos: 'http://www.w3.org/2004/02/skos/core#',
                    'schema:name': {
                        '@type': 'xsd:string',
                    },
                    'schema:description': {
                        '@type': 'xsd:string',
                    },
                    'skos:prefLabel': {
                        '@type': 'xsd:string',
                    },
                    'skos:altLabel': {
                        '@type': 'xsd:string',
                    },
                    'pav:createdOn': {
                        '@type': 'xsd:dateTime',
                    },
                    'pav:createdBy': {
                        '@type': '@id',
                    },
                    'pav:lastUpdatedOn': {
                        '@type': 'xsd:dateTime',
                    },
                    'oslc:modifiedBy': {
                        '@type': '@id',
                    },
                },
                title: 'catalogIdentifier field schema',
                description: 'catalogIdentifier field schema generated by the CEDAR Template Editor 2.6.0',
                _ui: {
                    inputType: 'link',
                },
                _valueConstraints: {
                    requiredValue: false,
                },
                properties: {
                    '@type': {
                        oneOf: [
                            {
                                type: 'string',
                                format: 'uri',
                            },
                            {
                                type: 'array',
                                minItems: 1,
                                items: {
                                    type: 'string',
                                    format: 'uri',
                                },
                                uniqueItems: true,
                            },
                        ],
                    },
                    'rdfs:label': {
                        type: [
                            'string',
                            'null',
                        ],
                    },
                    '@id': {
                        type: 'string',
                        format: 'uri',
                    },
                },
                additionalProperties: false,
                'pav:createdOn': '2022-02-01T11:19:21-08:00',
                'pav:createdBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
                'pav:lastUpdatedOn': '2022-02-01T11:19:21-08:00',
                'oslc:modifiedBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
                'schema:schemaVersion': '1.6.0',
                'schema:name': 'catalogIdentifier',
                'schema:description': 'Globally unique, persistent and resolvable identifier that identifies data catalogs that are part of the data catalog being described.',
                'skos:prefLabel': 'Catalog Identifier',
                '@id': 'https://repo.metadatacenter.org/template-fields/6e55cb3a-7406-4447-ad10-f13273ebde06',
                $schema: 'http://json-schema.org/draft-04/schema#',
            },
        },
    },
    required: [
        '@context',
        '@id',
        'schema:isBasedOn',
        'schema:name',
        'schema:description',
        'pav:createdOn',
        'pav:createdBy',
        'pav:lastUpdatedOn',
        'oslc:modifiedBy',
        'catalogTitle',
        'catalogDescription',
        'datasetIdentifier',
        'publisher',
        'catalogIdentifier',
    ],
    'schema:name': 'Data Catalog',
    'schema:description': 'DCAT v3 template for data catalog metadata',
    'pav:createdOn': '2021-09-23T22:48:16-07:00',
    'pav:createdBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
    'pav:lastUpdatedOn': '2022-02-01T11:19:21-08:00',
    'oslc:modifiedBy': 'https://metadatacenter.org/users/cb584e9d-cd34-44f0-9d67-10b217311750',
    'schema:schemaVersion': '1.6.0',
    additionalProperties: false,
    'pav:version': '0.0.1',
    'bibo:status': 'bibo:published',
    $schema: 'http://json-schema.org/draft-04/schema#',
});
