name: gh-actions-test

on: [push, pull_request]

jobs:
  fetch-dependencies-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Run es linting ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/node_modules
        key: cached_node_modules_${{ hashFiles('**/yarn.lock') }}
        restore-keys: cached_node_modules_
    - run: yarn --prefer-offline --frozen-lockfile --ignore-engines
    - run: yarn build:test

  lint:
    needs: fetch-dependencies-and-build
    steps:
    - run: yarn lint:es
    - run: yarn lint:ts
    - run: yarn lint:style
    - run: yarn lint:template

  test:
    needs: fetch-dependencies-and-build
    - run: yarn test:cover --path ./dist
  
  send-to-coverall:
    needs: test
    - run: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    
