name: gh-actions-test

on: [push, pull_request]

jobs:
  # fetch-dependencies:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Run es linting ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/node_modules
        key: cached_node_modules_${{ hashFiles('**/yarn.lock') }}
        restore-keys: cached_node_modules_
    - run: yarn
    - run: yarn lint:es
    - run: yarn lint:ts
    - run: yarn lint:style
    - run: yarn lint:template
    - run: yarn test
    # - run: npm run build --if-present
    # - run: npm test
